"""empty message

Revision ID: 4c32b038f2b
Revises: None
Create Date: 2016-01-10 18:17:13.253747

"""

# revision identifiers, used by Alembic.
revision = '4c32b038f2b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
